// examples/showcase/src/react/ControlsRail.tsx
import { FONT_STACKS, GAME_META, INERT_CONFIG_KEYS, metaOf, type GameId, type ThemeForm } from '../shared/meta';

const COLOR_KEYS = ['primary', 'secondary', 'background', 'text'] as const;

interface ControlsRailProps {
  themes: Record<GameId, ThemeForm>;
  selected: GameId;
  onSelect: (id: GameId) => void;
  onThemeChange: (id: GameId, patch: Partial<ThemeForm>) => void;
  onReset: (id: GameId) => void;
  playerName: string;
  onPlayerName: (name: string) => void;
  autoStart: boolean;
  onAutoStart: (value: boolean) => void;
}

export function ControlsRail({
  themes,
  selected,
  onSelect,
  onThemeChange,
  onReset,
  playerName,
  onPlayerName,
  autoStart,
  onAutoStart,
}: ControlsRailProps) {
  const theme = themes[selected];

  return (
    <aside className="panel panel--sticky">
      <div className="panel__head">
        <h3>Controls</h3>
        <span className="chip">props</span>
      </div>
      <div className="panel__body">
        <div className="field">
          <label htmlFor="react-player">setPlayerName()</label>
          <input
            id="react-player"
            type="text"
            value={playerName}
            placeholder="Ada"
            autoComplete="off"
            maxLength={24}
            onChange={(event) => onPlayerName(event.target.value)}
          />
          <p className="hint">Applied through the ref handle on all three games.</p>
        </div>

        <div className="field">
          <span className="field__label">autoStart prop</span>
          <div className="field__row">
            <button
              type="button"
              className="btn btn--sm"
              aria-pressed={autoStart}
              onClick={() => onAutoStart(!autoStart)}
            >
              {autoStart ? 'true — games run on mount' : 'false — idle until start()'}
            </button>
          </div>
        </div>

        <div className="fieldset">
          <p className="fieldset__title">
            theme — editing <span className="chip">{metaOf(selected).title.toLowerCase()}</span>
          </p>
          <div className="segmented">
            {GAME_META.map((meta) => (
              <button
                key={meta.id}
                type="button"
                className="btn btn--sm"
                aria-pressed={meta.id === selected}
                onClick={() => onSelect(meta.id)}
              >
                {meta.title}
              </button>
            ))}
          </div>
          <p className="hint">
            Editing a theme changes that game&apos;s <code>config</code> identity, which rebuilds the instance.
          </p>

          {COLOR_KEYS.map((key) => (
            <div className="field" key={key}>
              <label htmlFor={`react-${key}`}>{key}</label>
              <div className="field__row">
                <input
                  id={`react-${key}`}
                  type="color"
                  value={theme[key]}
                  onChange={(event) => onThemeChange(selected, { [key]: event.target.value })}
                />
                <span className="hex">{theme[key]}</span>
              </div>
            </div>
          ))}
        </div>

        <div className="fieldset">
          <p className="fieldset__title">typography</p>
          <div className="field">
            <label htmlFor="react-font">fontFamily</label>
            <select
              id="react-font"
              value={theme.fontFamily}
              onChange={(event) => onThemeChange(selected, { fontFamily: event.target.value })}
            >
              {FONT_STACKS.map((stack) => (
                <option key={stack.label} value={stack.value}>
                  {stack.label}
                </option>
              ))}
            </select>
          </div>
          <div className="field">
            <label htmlFor="react-large">fontSize.large — score text</label>
            <input
              id="react-large"
              type="number"
              min={8}
              max={72}
              value={theme.fontSizeLarge}
              onChange={(event) =>
                onThemeChange(selected, { fontSizeLarge: clampSize(event.target.value) })
              }
            />
          </div>
          <div className="field">
            <label htmlFor="react-small">fontSize.small — captions</label>
            <input
              id="react-small"
              type="number"
              min={8}
              max={72}
              value={theme.fontSizeSmall}
              onChange={(event) =>
                onThemeChange(selected, { fontSizeSmall: clampSize(event.target.value) })
              }
            />
          </div>
        </div>

        <div className="fieldset">
          <button type="button" className="btn btn--sm" onClick={() => onReset(selected)}>
            Reset this theme
          </button>
        </div>

        <details className="fieldset inert">
          <summary className="fieldset__title">Accepted by the constructor, ignored by these games</summary>
          {INERT_CONFIG_KEYS.map((item) => (
            <p key={item.key}>
              <code>{item.key}</code> — {item.detail}
            </p>
          ))}
        </details>
      </div>
    </aside>
  );
}

function clampSize(raw: string): number {
  const parsed = Number.parseInt(raw, 10);
  if (!Number.isFinite(parsed)) return 16;
  return Math.min(72, Math.max(8, parsed));
}

// examples/showcase/src/vue/ControlsRail.vue
<script setup lang="ts">
import { computed } from 'vue';
import { FONT_STACKS, GAME_META, INERT_CONFIG_KEYS, metaOf, type GameId, type ThemeForm } from '../shared/meta';

const COLOR_KEYS = ['primary', 'secondary', 'background', 'text'] as const;
type ColorKey = (typeof COLOR_KEYS)[number];

const props = defineProps<{
  themes: Record<GameId, ThemeForm>;
  selected: GameId;
  playerName: string;
  autoStart: boolean;
}>();

const emit = defineEmits<{
  select: [id: GameId];
  theme: [id: GameId, patch: Partial<ThemeForm>];
  player: [name: string];
  autoStart: [value: boolean];
  reset: [id: GameId];
}>();

const theme = computed(() => props.themes[props.selected]);

function patch(change: Partial<ThemeForm>): void {
  emit('theme', props.selected, change);
}

function onColor(key: ColorKey, event: Event): void {
  const next: Partial<ThemeForm> = {};
  next[key] = (event.target as HTMLInputElement).value;
  patch(next);
}

function onFont(event: Event): void {
  patch({ fontFamily: (event.target as HTMLSelectElement).value });
}

function onSize(key: 'fontSizeLarge' | 'fontSizeSmall', event: Event): void {
  const parsed = Number.parseInt((event.target as HTMLInputElement).value, 10);
  if (!Number.isFinite(parsed)) return;
  const next: Partial<ThemeForm> = {};
  next[key] = Math.min(72, Math.max(8, parsed));
  patch(next);
}
</script>

<template>
  <aside class="panel panel--sticky">
    <div class="panel__head">
      <h3>Controls</h3>
      <span class="chip">props &amp; events</span>
    </div>
    <div class="panel__body">
      <div class="field">
        <label for="vue-player">setPlayerName()</label>
        <input
          id="vue-player"
          type="text"
          :value="props.playerName"
          placeholder="Ada"
          autocomplete="off"
          maxlength="24"
          @input="emit('player', ($event.target as HTMLInputElement).value)"
        />
        <p class="hint">Applied through the exposed method on all three games.</p>
      </div>

      <div class="field">
        <span class="field__label">autoStart prop</span>
        <div class="field__row">
          <button
            type="button"
            class="btn btn--sm"
            :aria-pressed="props.autoStart"
            @click="emit('autoStart', !props.autoStart)"
          >
            {{ props.autoStart ? 'true — games run on mount' : 'false — idle until start()' }}
          </button>
        </div>
      </div>

      <div class="fieldset">
        <p class="fieldset__title">
          theme — editing <span class="chip">{{ metaOf(props.selected).title.toLowerCase() }}</span>
        </p>
        <div class="segmented">
          <button
            v-for="meta in GAME_META"
            :key="meta.id"
            type="button"
            class="btn btn--sm"
            :aria-pressed="meta.id === props.selected"
            @click="emit('select', meta.id)"
          >
            {{ meta.title }}
          </button>
        </div>
        <p class="hint">
          Editing a theme changes that game&apos;s <code>config</code> identity, which rebuilds the instance.
        </p>

        <div v-for="key in COLOR_KEYS" :key="key" class="field">
          <label :for="`vue-${key}`">{{ key }}</label>
          <div class="field__row">
            <input
              :id="`vue-${key}`"
              type="color"
              :value="theme[key]"
              @input="onColor(key, $event)"
            />
            <span class="hex">{{ theme[key] }}</span>
          </div>
        </div>
      </div>

      <div class="fieldset">
        <p class="fieldset__title">typography</p>
        <div class="field">
          <label for="vue-font">fontFamily</label>
          <select id="vue-font" :value="theme.fontFamily" @change="onFont">
            <option v-for="stack in FONT_STACKS" :key="stack.label" :value="stack.value">
              {{ stack.label }}
            </option>
          </select>
        </div>
        <div class="field">
          <label for="vue-large">fontSize.large — score text</label>
          <input
            id="vue-large"
            type="number"
            min="8"
            max="72"
            :value="theme.fontSizeLarge"
            @input="onSize('fontSizeLarge', $event)"
          />
        </div>
        <div class="field">
          <label for="vue-small">fontSize.small — captions</label>
          <input
            id="vue-small"
            type="number"
            min="8"
            max="72"
            :value="theme.fontSizeSmall"
            @input="onSize('fontSizeSmall', $event)"
          />
        </div>
      </div>

      <div class="fieldset">
        <button type="button" class="btn btn--sm" @click="emit('reset', props.selected)">
          Reset this theme
        </button>
      </div>

      <details class="fieldset inert">
        <summary class="fieldset__title">Accepted by the constructor, ignored by these games</summary>
        <p v-for="item in INERT_CONFIG_KEYS" :key="item.key">
          <code>{{ item.key }}</code> — {{ item.detail }}
        </p>
      </details>
    </div>
  </aside>
</template>
